# Generated by Django 4.2.9 on 2024-01-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0002_alter_statepopulation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statepopulation',
            name='state',
            field=models.TextField(max_length=250),
        ),
    ]
