# Generated by Django 4.2.9 on 2024-02-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0005_districtpopulation_delete_indianstates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictPopulation',
        ),
    ]
