# Generated by Django 4.2.6 on 2024-03-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0007_districtpopulation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistrictPopulation',
        ),
        migrations.DeleteModel(
            name='EVChargingLocation',
        ),
        migrations.DeleteModel(
            name='StatePopulation',
        ),
    ]
