# Generated by Django 5.2 on 2025-04-28 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actiontakenreport',
            old_name='date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='actiontakenreport',
            old_name='warden_notes',
            new_name='report',
        ),
        migrations.AddField(
            model_name='actiontakenreport',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('R', 'Rejected')], default='P', help_text='Current status of this ATR', max_length=1),
        ),
        migrations.AlterField(
            model_name='actiontakenreport',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint'),
        ),
    ]
